<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPPHtm0h\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPPHtm0h/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPPHtm0h.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPPHtm0h\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPPHtm0h\App_KernelDevDebugContainer([
    'container.build_hash' => 'PPHtm0h',
    'container.build_id' => '1eae3b4a',
    'container.build_time' => 1739764803,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPPHtm0h');
