<?php

namespace ContainerPPHtm0h;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Riwog4LService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.riwog4L' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.riwog4L'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\AuthController::register' => ['privates', '.service_locator.A84gqGd.App\\Controller\\AuthController::register()', 'getAuthControllerregisterService', true],
            'App\\Controller\\AuthController::login' => ['privates', '.service_locator.Ytrjb12.App\\Controller\\AuthController::login()', 'getAuthControllerloginService', true],
            'App\\Controller\\UsernameController::changeUsername' => ['privates', '.service_locator.Zhu40_0.App\\Controller\\UsernameController::changeUsername()', 'getUsernameControllerchangeUsernameService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\AuthController:register' => ['privates', '.service_locator.A84gqGd.App\\Controller\\AuthController::register()', 'getAuthControllerregisterService', true],
            'App\\Controller\\AuthController:login' => ['privates', '.service_locator.Ytrjb12.App\\Controller\\AuthController::login()', 'getAuthControllerloginService', true],
            'App\\Controller\\UsernameController:changeUsername' => ['privates', '.service_locator.Zhu40_0.App\\Controller\\UsernameController::changeUsername()', 'getUsernameControllerchangeUsernameService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\AuthController::register' => '?',
            'App\\Controller\\AuthController::login' => '?',
            'App\\Controller\\UsernameController::changeUsername' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\AuthController:register' => '?',
            'App\\Controller\\AuthController:login' => '?',
            'App\\Controller\\UsernameController:changeUsername' => '?',
        ]);
    }
}
