<?php

namespace ContainerPPHtm0h;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUsernameControllerchangeUsernameService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Zhu40_0.App\Controller\UsernameController::changeUsername()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Zhu40_0.App\\Controller\\UsernameController::changeUsername()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'hub' => ['privates', 'mercure.hub.default.traceable', 'getMercure_Hub_Default_TraceableService', false],
        ], [
            'hub' => '?',
        ]))->withContext('App\\Controller\\UsernameController::changeUsername()', $container);
    }
}
